apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: abyul-ingress
  namespace: abyul
spec:
  ingressClassName: nginx
  rules:
    - host: abyul.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: bff-server
                port:
                  number: 4000
