apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - postgres.yaml
  - redis.yaml
  - nats.yaml
  - loki.yaml
  - grafana.yaml
  - promtail.yaml
  - bff-server.yaml
  - api-gateway.yaml
  - user-service.yaml
  - worker.yaml
  - engine-audio-ingest.yaml
  - ingress.yaml
