apiVersion: v1
kind: Secret
metadata:
  name: vox2vocal-secret
  namespace: vox2vocal
type: Opaque
stringData:
  POSTGRES_USER: vox2vocal
  POSTGRES_PASSWORD: vox2vocal
  POSTGRES_DB: vox2vocal
  DATABASE_URL: postgresql://vox2vocal:vox2vocal@postgres:5432/vox2vocal?schema=users
