apiVersion: v1
kind: Secret
metadata:
  name: abyul-secret
  namespace: abyul
type: Opaque
stringData:
  POSTGRES_USER: abyul
  POSTGRES_PASSWORD: abyul
  POSTGRES_DB: abyul
  DATABASE_URL: postgresql://abyul:abyul@postgres:5432/abyul?schema=users
