apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: vox2vocal
spec:
  selector:
    app: user-service
  ports:
    - name: http
      port: 3002
      targetPort: 3002
    - name: grpc
      port: 50051
      targetPort: 50051
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: vox2vocal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: vox2vocal/user-service:local
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3002
            - containerPort: 50051
          env:
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: vox2vocal-config
                  key: NODE_ENV
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: vox2vocal-config
                  key: USER_SERVICE_HTTP_PORT
            - name: GRPC_URL
              valueFrom:
                configMapKeyRef:
                  name: vox2vocal-config
                  key: USER_SERVICE_GRPC_BIND_URL
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: vox2vocal-secret
                  key: DATABASE_URL
          readinessProbe:
            httpGet:
              path: /health
              port: 3002
            initialDelaySeconds: 10
            periodSeconds: 10
