apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  namespace: vox2vocal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
        - name: worker
          image: vox2vocal/worker:local
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3003
          env:
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: vox2vocal-config
                  key: NODE_ENV
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: vox2vocal-config
                  key: WORKER_PORT
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: vox2vocal-config
                  key: REDIS_HOST
            - name: REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  name: vox2vocal-config
                  key: REDIS_PORT
          readinessProbe:
            httpGet:
              path: /health
              port: 3003
            initialDelaySeconds: 10
            periodSeconds: 10
